import type { ReactNode } from 'react';
import { NavLink, Link } from 'react-router-dom';
import { BookOpen, BriefcaseBusiness, ClipboardList, House, Layers3, Menu, Moon, Sun, Workflow, X } from 'lucide-react';
import { useState } from 'react';
import { useAppStore } from '@/shared/store/app-store';

const items = [ ['/', House, 'Главная'], ['/projects', BriefcaseBusiness, 'Проекты'], ['/p3', Layers3, 'P3.express'], ['/sdlc', Workflow, 'SDLC'], ['/knowledge', BookOpen, 'База знаний'], ['/tasks', ClipboardList, 'Мои задачи'] ] as const;
export function Shell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const { theme, toggleTheme } = useAppStore();
  return <div className="min-h-screen bg-[var(--av-bg)] text-[var(--av-text)] lg:pl-60"><a href="#content" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:p-3 focus:bg-[var(--av-gold)] focus:text-black">К содержимому</a><header className="lg:hidden sticky top-0 z-30 flex items-center justify-between border-b avari-divider bg-[var(--av-bg)] px-4 py-2"><Link to="/" className="font-semibold">✦ Avari <span className="avari-gold">P3</span></Link><button className="p-2" onClick={() => setOpen(!open)} aria-label={open ? 'Закрыть меню' : 'Открыть меню'} aria-expanded={open}>{open ? <X /> : <Menu />}</button></header><aside className={`${open ? 'block' : 'hidden'} fixed inset-y-0 left-0 z-40 w-60 border-r avari-divider bg-[var(--av-surface)] lg:block`}><div className="flex h-full flex-col p-4"><Link to="/" className="mb-8 p-2 text-xl font-semibold" onClick={() => setOpen(false)}>✦ Avari <span className="avari-gold">P3</span></Link><nav aria-label="Основная навигация" className="space-y-1">{items.map(([url, Icon, title]) => <NavLink key={url} to={url} end={url === '/'} onClick={() => setOpen(false)} className={({ isActive }) => `flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm ${isActive ? 'bg-[var(--av-gold)] text-[var(--av-on-accent)]' : 'avari-secondary hover:bg-[var(--av-surface-hover)]'}`}><Icon size={18} aria-hidden="true" />{title}</NavLink>)}</nav><div className="mt-auto border-t avari-divider pt-4"><button onClick={toggleTheme} className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm avari-secondary hover:bg-[var(--av-surface-hover)]">{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}{theme === 'dark' ? 'Светлая тема' : 'Тёмная тема'}</button><p className="px-3 pt-4 text-xs avari-muted">Личное рабочее пространство</p></div></div></aside>{open && <button aria-label="Закрыть меню" className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={() => setOpen(false)} />}<main id="content" className="mx-auto max-w-7xl px-4 py-6 sm:px-7 sm:py-9">{children}</main></div>;
}
export function Crumbs({ items }: { items: { title: string; href?: string }[] }) { return <nav aria-label="Хлебные крошки" className="mb-5 flex flex-wrap items-center gap-2 text-xs avari-muted"><Link to="/" className="hover:underline">Главная</Link>{items.map((item, i) => <span key={i} className="inline-flex items-center gap-2"><span aria-hidden="true">/</span>{item.href ? <Link to={item.href} className="hover:underline">{item.title}</Link> : <span aria-current="page" className="avari-secondary">{item.title}</span>}</span>)}</nav> }
