run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - bodyclose
    - gocritic
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
