import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useQueries } from '@tanstack/react-query';
import { AlertTriangle, ArrowRight, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { useActions, useP3Mutation, useProjects } from '@/entities/p3/queries';
import type { ProjectSummary } from '@/entities/p3/types';
import { p3Api } from '@/entities/p3/api';
import { Button } from '@/shared/components/Button';
import { Card } from '@/shared/components/Card';
import { Modal } from '@/shared/components/Modal';
import { Crumbs } from '@/app/p3/Shell';
import { DateLabel, Empty, Field, fieldClass, PageTitle, ProjectCard, QueryState, Section, Status } from './ui';

function NewProject({ open, close }: { open: boolean; close: () => void }) {
  const navigate = useNavigate();
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [due, setDue] = useState('');
  const mutation = useP3Mutation(p3Api.createProject);
  return <Modal isOpen={open} onClose={close} title="Новый проект" description="Фазы и шаги P3.express будут добавлены автоматически."><form onSubmit={e => { e.preventDefault(); mutation.mutate({ name: name.trim(), description: description.trim(), due_date: due || null }, { onSuccess: project => { close(); setName(''); setDescription(''); setDue(''); toast.success('Проект создан'); navigate(`/projects/${project.id}`) } }) }}><Field label="Название"><input className={fieldClass} required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Описание"><textarea className={fieldClass} rows={3} value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="Срок"><input className={fieldClass} type="date" value={due} onChange={e => setDue(e.target.value)} /></Field><Button type="submit" isLoading={mutation.isPending}>Создать проект</Button></form></Modal>
}
function RecentActivity({ projects }: { projects: ProjectSummary[] }) { const queries=useQueries({queries:projects.map(p=>({queryKey:['p3','project',p.id],queryFn:()=>p3Api.project(p.id)}))}); const rows=queries.flatMap(q=>q.data ? (q.data.activity||[]).map(a=>({...a,project:q.data!})) : []).sort((a,b)=>(b.created_at||'').localeCompare(a.created_at||'')).slice(0,8); return <Section title="Лента изменений">{queries.some(q=>q.isLoading) && <Card role="status">Загрузка изменений…</Card>}{rows.length ? <Card className="divide-y avari-divider">{rows.map(a=><Link key={a.id} to={`/projects/${a.project.id}`} className="block py-2 hover:underline"><strong>{a.project.name}</strong><span className="ml-2 avari-secondary">{a.description || a.text || a.type}</span><small className="ml-2 avari-muted">{a.created_at && new Date(a.created_at).toLocaleString('ru-RU')}</small></Link>)}</Card> : !queries.some(q=>q.isLoading) && <Empty text="Изменений пока нет." />}</Section> }
export function DashboardPage() {
  const projects = useProjects(); const actions = useActions();
  const active = (projects.data || []).filter(p => !p.archived);
  const attention = active.filter(p => p.open_blockers || p.rag_status === 'red' || p.rag_status === 'yellow');
  const upcoming = (actions.data || []).filter(a => !a.done).sort((a,b) => (a.due_date || '9999').localeCompare(b.due_date || '9999')).slice(0,5);
  return <><PageTitle title="Главная" eyebrow="Обзор портфеля">Состояние проектов и ближайшие действия.</PageTitle><QueryState loading={projects.isLoading || actions.isLoading} error={(projects.error || actions.error) as Error | null} retry={() => { projects.refetch(); actions.refetch() }} />{projects.data && actions.data && <><Section title="Важные вопросы">{attention.length ? <div className="grid gap-3">{attention.map(p => <Link key={p.id} to={`/projects/${p.id}`}><Card className="flex items-center justify-between gap-4 border-[var(--av-danger)]/50 hover:bg-[var(--av-surface-hover)]"><div className="flex items-center gap-3"><AlertTriangle size={20} className="text-[var(--av-danger)]" /><div><strong>{p.name}</strong><p className="text-sm avari-secondary">{p.open_blockers ? `${p.open_blockers} открытых блокеров` : 'Требует внимания'}</p></div></div><Status value={p.rag_status} /></Card></Link>)}</div> : <Empty text="Сейчас нет проектов с рисками или блокерами." />}</Section><Section title="Ближайшие действия" action={<Link to="/tasks" className="text-sm avari-gold">Все задачи →</Link>}>{upcoming.length ? <Card className="divide-y avari-divider">{upcoming.map(a => <Link key={a.id} to={`/projects/${a.project_id}`} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0 hover:underline"><span>{a.title}<small className="ml-2 avari-muted">{active.find(p => p.id === a.project_id)?.name}</small></span><DateLabel value={a.due_date} /></Link>)}</Card> : <Empty text="Ближайших действий нет." />}</Section><RecentActivity projects={active} /><Section title="Активные проекты" action={<Link to="/projects" className="text-sm avari-gold">Все проекты →</Link>}>{active.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.map(p => <ProjectCard key={p.id} project={p} />)}</div> : <Empty text="Пока нет проектов." action={<Link to="/projects" className="avari-gold">Создать первый проект <ArrowRight className="inline" size={16} /></Link>} />}</Section></>}</>
}
export function ProjectsPage() {
  const projects = useProjects(); const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [rag, setRag] = useState(''); const [phase, setPhase] = useState(''); const [sdlc, setSdlc] = useState(''); const [showArchived, setShowArchived] = useState(false);
  const list = (projects.data || []).filter(p => (showArchived || !p.archived) && p.name.toLowerCase().includes(search.toLowerCase()) && (!rag || p.rag_status === rag) && (!phase || p.current_phase === phase) && (!sdlc || p.current_sdlc_stage === sdlc));
  return <><Crumbs items={[{ title: 'Проекты' }]} /><PageTitle title="Проекты" eyebrow="Портфель" action={<Button onClick={() => setOpen(true)} leftIcon={<Plus size={17} />}>Новый проект</Button>}>Каталог проектов, их сроки и текущее состояние.</PageTitle><Card className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label><span className="text-xs avari-secondary">Поиск</span><input className={fieldClass} value={search} onChange={e => setSearch(e.target.value)} placeholder="Название" /></label><label><span className="text-xs avari-secondary">Статус</span><select className={fieldClass} value={rag} onChange={e => setRag(e.target.value)}><option value="">Все</option><option value="green">В норме</option><option value="yellow">Риск</option><option value="red">Критично</option></select></label><label><span className="text-xs avari-secondary">Фаза P3</span><select className={fieldClass} value={phase} onChange={e => setPhase(e.target.value)}><option value="">Все</option>{'ABCDEFG'.split('').map(x => <option key={x}>{x}</option>)}</select></label><label><span className="text-xs avari-secondary">SDLC</span><select className={fieldClass} value={sdlc} onChange={e => setSdlc(e.target.value)}><option value="">Все</option>{[...new Set((projects.data || []).map(p => p.current_sdlc_stage).filter(Boolean))].map(x => <option key={x!}>{x}</option>)}</select></label><label className="flex items-center gap-2 self-end min-h-11"><input type="checkbox" checked={showArchived} onChange={e => setShowArchived(e.target.checked)} />Архивные</label></Card><QueryState loading={projects.isLoading} error={projects.error as Error | null} retry={() => projects.refetch()} />{projects.data && (list.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map(p => <ProjectCard key={p.id} project={p} />)}</div> : <Empty text={projects.data.length ? 'По фильтрам ничего не найдено.' : 'Проектов пока нет.'} />)}<NewProject open={open} close={() => setOpen(false)} /></>
}
