import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { AlertCircle, ArrowRight, CalendarDays } from 'lucide-react';
import { Badge } from '@/shared/components/Badge';
import { Card } from '@/shared/components/Card';
import type { ProjectSummary } from '@/entities/p3/types';

export function PageTitle({ eyebrow, title, children, action }: { eyebrow?: string; title: string; children?: ReactNode; action?: ReactNode }) {
  return <header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] avari-gold">{eyebrow || 'Рабочее пространство'}</p><h1 className="text-3xl sm:text-4xl leading-tight">{title}</h1>{children && <p className="mt-2 avari-secondary">{children}</p>}</div>{action}</header>;
}
export function Section({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <section className="mb-8"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-xl sm:text-2xl">{title}</h2>{action}</div>{children}</section> }
export function Empty({ text, action }: { text: string; action?: ReactNode }) { return <Card className="text-center py-10"><p className="avari-secondary">{text}</p>{action && <div className="mt-4">{action}</div>}</Card> }
export function QueryState({ loading, error, retry }: { loading: boolean; error?: Error | null; retry?: () => void }) { if (loading) return <Card role="status" className="animate-pulse">Загрузка данных…</Card>; if (error) return <Card role="alert" className="border-[var(--av-danger)]"><div className="flex items-center gap-2 text-[var(--av-danger)]"><AlertCircle size={18} />Не удалось загрузить данные: {error.message}</div>{retry && <button className="mt-3 underline" onClick={retry}>Повторить</button>}</Card>; return null }
export function Status({ value }: { value?: string | null }) { const v = value || 'todo'; const labels: Record<string,string> = { todo:'Не начато', not_started:'Не начато', in_progress:'В работе', blocked:'Блокировано', done:'Готово', green:'В норме', yellow:'Риск', red:'Критично' }; const variant = v === 'done' || v === 'green' ? 'success' : v === 'blocked' || v === 'red' ? 'danger' : v === 'in_progress' || v === 'yellow' ? 'warning' : 'neutral'; return <Badge variant={variant}>{labels[v] || v}</Badge> }
export function Progress({ value }: { value?: number }) { const n = Math.max(0, Math.min(100, Number(value) || 0)); return <div className="flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-[var(--av-surface-raised)]" role="progressbar" aria-valuenow={n} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-[var(--av-gold)]" style={{ width: `${n}%` }} /></div><span className="text-sm tabular-nums avari-secondary">{n}%</span></div> }
export function DateLabel({ value }: { value?: string | null }) { if (!value) return <span className="avari-muted">Без срока</span>; return <span className="inline-flex items-center gap-1"><CalendarDays size={14} aria-hidden="true" />{new Date(value + 'T00:00:00').toLocaleDateString('ru-RU')}</span> }
export function ProjectCard({ project }: { project: ProjectSummary }) { return <Link to={`/projects/${project.id}`} className="block rounded-2xl focus-visible:outline outline-2 outline-[var(--av-cyan)]"><Card className="h-full avari-interactive hover:border-[var(--av-gold)]"><div className="flex items-start justify-between gap-2"><div><p className="text-xs uppercase tracking-widest avari-gold">{project.current_phase ? `P3 · ${project.current_phase}` : 'Проект'}</p><h3 className="mt-1 text-xl">{project.name}</h3></div><Status value={project.rag_status} /></div><p className="mt-2 min-h-12 text-sm avari-secondary line-clamp-2">{project.description || 'Описание проекта пока не добавлено.'}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs avari-secondary"><span>SDLC: {project.current_sdlc_stage || '—'}</span><DateLabel value={project.due_date} /></div><div className="mt-4"><Progress value={project.progress} /></div><div className="mt-4 flex justify-between text-xs"><span className={project.open_blockers ? 'text-[var(--av-danger)]' : 'avari-muted'}>{project.open_blockers ? `Блокеры: ${project.open_blockers}` : 'Нет блокеров'}</span><span className="inline-flex items-center gap-1 avari-gold">Открыть <ArrowRight size={14} /></span></div></Card></Link> }
export const fieldClass = 'w-full min-h-11 rounded-lg border border-[var(--av-border-control)] bg-[var(--av-bg)] px-3 py-2 text-[var(--av-text)]';
export function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block mb-3"><span className="mb-1 block text-sm avari-secondary">{label}</span>{children}</label> }
